/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/flug/flug-edit/flug-edit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../../../app/flug/services/flug.service';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '@angular/core/src/change_detection/change_detection_util';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/common/src/directives/ng_if';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/ng_model';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_FlugEditComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FlugEditComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.FlugEditComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FlugEditComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FlugEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FlugEditComponent>;
  _FlugEditComponent_0_3:Wrapper_FlugEditComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugEditComponent_Host0,renderType_FlugEditComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FlugEditComponent0(this.viewUtils,this,0,this._el_0);
    this._FlugEditComponent_0_3 = new Wrapper_FlugEditComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.FlugService,this.parentIndex));
    this.compView_0.create(this._FlugEditComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FlugEditComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FlugEditComponent) && (0 === requestNodeIndex))) { return this._FlugEditComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FlugEditComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FlugEditComponentNgFactory:import7.ComponentFactory<import0.FlugEditComponent> = new import7.ComponentFactory<import0.FlugEditComponent>('ng-component',View_FlugEditComponent_Host0,import0.FlugEditComponent);
const styles_FlugEditComponent:any[] = ([] as any[]);
class View_FlugEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugEditComponent1,renderType_FlugEditComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import11.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','color:red; font-weight: bold'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'\n    ',this.parentView.context.message,'\n');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_FlugEditComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_FlugEditComponent,{});
export class View_FlugEditComponent0 extends import1.AppView<import0.FlugEditComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import10.ViewContainer;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import12.Wrapper_NgIf;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_10_4:any[];
  _NgModel_10_5:import14.Wrapper_NgModel;
  _NgControl_10_6:any;
  _NgControlStatus_10_7:import15.Wrapper_NgControlStatus;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _DefaultValueAccessor_21_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _NgModel_21_5:import14.Wrapper_NgModel;
  _NgControl_21_6:any;
  _NgControlStatus_21_7:import15.Wrapper_NgControlStatus;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _DefaultValueAccessor_29_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_29_4:any[];
  _NgModel_29_5:import14.Wrapper_NgModel;
  _NgControl_29_6:any;
  _NgControlStatus_29_7:import15.Wrapper_NgControlStatus;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _DefaultValueAccessor_37_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_37_4:any[];
  _NgModel_37_5:import14.Wrapper_NgModel;
  _NgControl_37_6:any;
  _NgControlStatus_37_7:import15.Wrapper_NgControlStatus;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugEditComponent0,renderType_FlugEditComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'FlugEdit',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_3 = new import10.ViewContainer(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import16.TemplateRef_(this,3,this._anchor_3);
    this._NgIf_3_6 = new import12.Wrapper_NgIf(this._vc_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Id',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_5,'input',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._DefaultValueAccessor_10_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_10));
    this._NG_VALUE_ACCESSOR_10_4 = [this._DefaultValueAccessor_10_3.context];
    this._NgModel_10_5 = new import14.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_10_4);
    this._NgControl_10_6 = this._NgModel_10_5.context;
    this._NgControlStatus_10_7 = new import15.Wrapper_NgControlStatus(this._NgControl_10_6);
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_5,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Leere Id oder 0 für neuen Datensatz',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Von',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_16,'input',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._DefaultValueAccessor_21_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._DefaultValueAccessor_21_3.context];
    this._NgModel_21_5 = new import14.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._NgModel_21_5.context;
    this._NgControlStatus_21_7 = new import15.Wrapper_NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Von',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'input',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._DefaultValueAccessor_29_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_29));
    this._NG_VALUE_ACCESSOR_29_4 = [this._DefaultValueAccessor_29_3.context];
    this._NgModel_29_5 = new import14.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_4);
    this._NgControl_29_6 = this._NgModel_29_5.context;
    this._NgControlStatus_29_7 = new import15.Wrapper_NgControlStatus(this._NgControl_29_6);
    this._text_30 = this.renderer.createText(this._el_24,'\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Datum',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_32,'input',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._DefaultValueAccessor_37_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_37));
    this._NG_VALUE_ACCESSOR_37_4 = [this._DefaultValueAccessor_37_3.context];
    this._NgModel_37_5 = new import14.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_4);
    this._NgControl_37_6 = this._NgModel_37_5.context;
    this._NgControlStatus_37_7 = new import15.Wrapper_NgControlStatus(this._NgControl_37_6);
    this._text_38 = this.renderer.createText(this._el_32,'\n',(null as any));
    this._text_39 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Speichern',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_5.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_21));
    this._NgModel_21_5.subscribe(this,this.eventHandler(this.handleEvent_21),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_29));
    this._NgModel_29_5.subscribe(this,this.eventHandler(this.handleEvent_29),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_37));
    this._NgModel_37_5.subscribe(this,this.eventHandler(this.handleEvent_37),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_42));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import18.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6.context; }
    if (((token === import19.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_4; }
    if (((token === import21.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_5.context; }
    if (((token === import22.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_6; }
    if (((token === import23.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_7.context; }
    if (((token === import19.DefaultValueAccessor) && (21 === requestNodeIndex))) { return this._DefaultValueAccessor_21_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (21 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import21.NgModel) && (21 === requestNodeIndex))) { return this._NgModel_21_5.context; }
    if (((token === import22.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_6; }
    if (((token === import23.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_7.context; }
    if (((token === import19.DefaultValueAccessor) && (29 === requestNodeIndex))) { return this._DefaultValueAccessor_29_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (29 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_29_4; }
    if (((token === import21.NgModel) && (29 === requestNodeIndex))) { return this._NgModel_29_5.context; }
    if (((token === import22.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_6; }
    if (((token === import23.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_7.context; }
    if (((token === import19.DefaultValueAccessor) && (37 === requestNodeIndex))) { return this._DefaultValueAccessor_37_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_4; }
    if (((token === import21.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_5.context; }
    if (((token === import22.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_6; }
    if (((token === import23.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.message;
    this._NgIf_3_6.check_ngIf(currVal_3_0_0,throwOnChange,false);
    this._NgIf_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    this._DefaultValueAccessor_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = this.context.flug.id;
    this._NgModel_10_5.check_model(currVal_10_1_0,throwOnChange,false);
    this._NgModel_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    this._NgControlStatus_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    this._DefaultValueAccessor_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_21_1_0:any = this.context.flug.abflugort;
    this._NgModel_21_5.check_model(currVal_21_1_0,throwOnChange,false);
    this._NgModel_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_7.ngDoCheck(this,this._el_21,throwOnChange);
    this._DefaultValueAccessor_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_29_1_0:any = this.context.flug.zielort;
    this._NgModel_29_5.check_model(currVal_29_1_0,throwOnChange,false);
    this._NgModel_29_5.ngDoCheck(this,this._el_29,throwOnChange);
    this._NgControlStatus_29_7.ngDoCheck(this,this._el_29,throwOnChange);
    this._DefaultValueAccessor_37_3.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_37_1_0:any = this.context.flug.datum;
    this._NgModel_37_5.check_model(currVal_37_1_0,throwOnChange,false);
    this._NgModel_37_5.ngDoCheck(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_7.ngDoCheck(this,this._el_37,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_10_7.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_21_7.checkHost(this,this,this._el_21,throwOnChange);
    this._NgControlStatus_29_7.checkHost(this,this,this._el_29,throwOnChange);
    this._NgControlStatus_37_7.checkHost(this,this,this._el_37,throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
    this._NgModel_10_5.ngOnDestroy();
    this._NgModel_21_5.ngOnDestroy();
    this._NgModel_29_5.ngOnDestroy();
    this._NgModel_37_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 3)) { return new View_FlugEditComponent1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    return (null as any);
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.flug.id = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_21_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.flug.abflugort = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_29_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.flug.zielort = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_37_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.flug.datum = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}