/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/flug/flug-buchen/flug-buchen.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../app/flug/services/flug.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/http/src/http';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/router/src/router_outlet_map';
import * as import17 from '@angular/core/src/linker/component_factory_resolver';
import * as import18 from '@angular/router/src/directives/router_link';
import * as import19 from '@angular/router/src/directives/router_outlet';
export class Wrapper_FlugBuchenComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FlugBuchenComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FlugBuchenComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FlugBuchenComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FlugBuchenComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FlugBuchenComponent>;
  _FlugBuchenComponent_0_3:Wrapper_FlugBuchenComponent;
  __FlugService_0_4:import5.FlugService;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugBuchenComponent_Host0,renderType_FlugBuchenComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _FlugService_0_4():import5.FlugService {
    if ((this.__FlugService_0_4 == null)) { (this.__FlugService_0_4 = new import5.FlugService(this.injectorGet(import8.Http,this.parentIndex))); }
    return this.__FlugService_0_4;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FlugBuchenComponent0(this.viewUtils,this,0,this._el_0);
    this._FlugBuchenComponent_0_3 = new Wrapper_FlugBuchenComponent();
    this.compView_0.create(this._FlugBuchenComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._FlugBuchenComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FlugBuchenComponent) && (0 === requestNodeIndex))) { return this._FlugBuchenComponent_0_3.context; }
    if (((token === import5.FlugService) && (0 === requestNodeIndex))) { return this._FlugService_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FlugBuchenComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FlugBuchenComponentNgFactory:import9.ComponentFactory<import0.FlugBuchenComponent> = new import9.ComponentFactory<import0.FlugBuchenComponent>('ng-component',View_FlugBuchenComponent_Host0,import0.FlugBuchenComponent);
const styles_FlugBuchenComponent:any[] = ([] as any[]);
var renderType_FlugBuchenComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_FlugBuchenComponent,{});
export class View_FlugBuchenComponent0 extends import1.AppView<import0.FlugBuchenComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _RouterLinkWithHref_6_3:import10.Wrapper_RouterLinkWithHref;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import10.Wrapper_RouterLinkWithHref;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _vc_18:import11.ViewContainer;
  _RouterOutlet_18_5:import12.Wrapper_RouterOutlet;
  _text_19:any;
  _text_20:any;
  _arr_25:any;
  _arr_26:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugBuchenComponent0,renderType_FlugBuchenComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_25 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_26 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-sm-3'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'ul',new import3.InlineArray4(4,'class','nav nav-pills nav-stacked','style','margin-top:20px;'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_5,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_6_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_7 = this.renderer.createText(this._el_6,'Flug auswählen',(null as any));
    this._text_8 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_3,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_10,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_11_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import13.Router,this.parentIndex),this.parentView.injectorGet(import14.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import15.LocationStrategy,this.parentIndex));
    this._text_12 = this.renderer.createText(this._el_11,'Passagier auswählen',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-sm-9'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_18 = new import11.ViewContainer(18,16,this,this._el_18);
    this._RouterOutlet_18_5 = new import12.Wrapper_RouterOutlet(this.parentView.injectorGet(import16.RouterOutletMap,this.parentIndex),this._vc_18.vcRef,this.parentView.injectorGet(import17.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.RouterLinkWithHref) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkWithHref_6_3.context; }
    if (((token === import18.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3.context; }
    if (((token === import19.RouterOutlet) && (18 === requestNodeIndex))) { return this._RouterOutlet_18_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = this._arr_25('flug-suchen');
    this._RouterLinkWithHref_6_3.check_routerLink(currVal_6_0_0,throwOnChange,false);
    this._RouterLinkWithHref_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_11_0_0:any = this._arr_26('passagier-suchen');
    this._RouterLinkWithHref_11_3.check_routerLink(currVal_11_0_0,throwOnChange,false);
    this._RouterLinkWithHref_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._RouterOutlet_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_6_3.checkHost(this,this,this._el_6,throwOnChange);
    this._RouterLinkWithHref_11_3.checkHost(this,this,this._el_11,throwOnChange);
  }
  destroyInternal():void {
    this._vc_18.destroyNestedViews();
    this._RouterLinkWithHref_6_3.ngOnDestroy();
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this._RouterOutlet_18_5.ngOnDestroy();
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_6_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_11_3.handleEvent(eventName,$event) && result);
    return result;
  }
}