/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '../../app/flug/flug.module';
import * as import10 from '@angular/material/core/compatibility/default-mode';
import * as import11 from '@angular/material/core/ripple/ripple';
import * as import12 from '@angular/material/button/button';
import * as import13 from '@angular/material/card/card';
import * as import14 from '@angular/material/chips/chip-list';
import * as import15 from '@angular/material/checkbox/checkbox';
import * as import16 from '@angular/material/core/line/line';
import * as import17 from '@angular/material/grid-list/grid-list';
import * as import18 from '@angular/material/core/platform/index';
import * as import19 from '@angular/material/input/input';
import * as import20 from '@angular/material/list/list';
import * as import21 from '@angular/material/progress-bar/progress-bar';
import * as import22 from '@angular/material/progress-spinner/progress-spinner';
import * as import23 from '@angular/material/core/portal/portal-directives';
import * as import24 from '@angular/material/core/overlay/overlay-directives';
import * as import25 from '@angular/material/select/index';
import * as import26 from '@angular/material/core/a11y/index';
import * as import27 from '@angular/material/sidenav/sidenav';
import * as import28 from '@angular/material/core/observe-content/observe-content';
import * as import29 from '@angular/material/tabs/tab-group';
import * as import30 from '@angular/material/toolbar/toolbar';
import * as import31 from '@angular/material/core/projection/projection';
import * as import32 from '@angular/material/core/rtl/dir';
import * as import33 from '@angular/material/button-toggle/button-toggle';
import * as import34 from '@angular/material/dialog/index';
import * as import35 from '@angular/material/icon/icon';
import * as import36 from '@angular/material/menu/menu';
import * as import37 from '@angular/material/radio/radio';
import * as import38 from '@angular/material/slider/slider';
import * as import39 from '@angular/material/slide-toggle/slide-toggle';
import * as import40 from '@angular/material/snack-bar/snack-bar';
import * as import41 from '@angular/material/tooltip/tooltip';
import * as import42 from '@angular/material/module';
import * as import43 from '@angular/common/src/localization';
import * as import44 from '@angular/core/src/application_init';
import * as import45 from '@angular/core/src/testability/testability';
import * as import46 from '@angular/core/src/application_ref';
import * as import47 from '@angular/core/src/linker/compiler';
import * as import48 from '@angular/material/core/gestures/gesture-config';
import * as import49 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import50 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import51 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import52 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import53 from '@angular/core/src/animation/animation_queue';
import * as import54 from '@angular/core/src/linker/view_utils';
import * as import55 from '@angular/platform-browser/src/browser/title';
import * as import56 from '@angular/http/src/backends/browser_xhr';
import * as import57 from '@angular/http/src/base_response_options';
import * as import58 from '@angular/http/src/backends/xhr_backend';
import * as import59 from '@angular/http/src/base_request_options';
import * as import60 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import61 from '../../app/flug/services/flug.service';
import * as import62 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import63 from '@angular/material/core/platform/platform';
import * as import64 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import65 from '@angular/material/core/overlay/overlay-container';
import * as import66 from '@angular/material/core/overlay/overlay';
import * as import67 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import68 from '@angular/material/core/a11y/interactivity-checker';
import * as import69 from '@angular/material/core/a11y/live-announcer';
import * as import70 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import71 from '@angular/material/dialog/dialog';
import * as import72 from '@angular/material/icon/icon-registry';
import * as import73 from '@angular/common/src/location/location';
import * as import74 from '@angular/router/src/url_tree';
import * as import75 from '@angular/router/src/router_outlet_map';
import * as import76 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import77 from '@angular/router/src/router_preloader';
import * as import78 from '@angular/core/src/di/injector';
import * as import79 from './flug/flug-buchen/flug-buchen.component.ngfactory';
import * as import80 from './flug/flug-suchen/flug-suchen.component.ngfactory';
import * as import81 from './flug/passagier-suchen/passagier.suchen.component.ngfactory';
import * as import82 from './flug/flug-edit/flug-edit.component.ngfactory';
import * as import83 from '../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import84 from '../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import85 from '../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import86 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import87 from './home/home.component.ngfactory';
import * as import88 from './app.component.ngfactory';
import * as import89 from '@angular/core/src/application_tokens';
import * as import90 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import91 from '@angular/platform-browser/src/dom/events/key_events';
import * as import92 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import93 from '@angular/core/src/zone/ng_zone';
import * as import94 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import95 from '../../app/flug/flug-buchen/flug-buchen.component';
import * as import96 from '../../app/flug/flug-suchen/flug-suchen.component';
import * as import97 from '../../app/flug/passagier-suchen/passagier.suchen.component';
import * as import98 from '../../app/flug/flug-edit/flug-edit.component';
import * as import99 from '../../app/home/home.component';
import * as import100 from '@angular/common/src/location/platform_location';
import * as import101 from '@angular/common/src/location/location_strategy';
import * as import102 from '@angular/router/src/url_handling_strategy';
import * as import103 from '@angular/router/src/route_reuse_strategy';
import * as import104 from '@angular/router/src/router';
import * as import105 from '@angular/core/src/console';
import * as import106 from '@angular/core/src/i18n/tokens';
import * as import107 from '@angular/core/src/error_handler';
import * as import108 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import109 from '@angular/platform-browser/src/dom/animation_driver';
import * as import110 from '@angular/core/src/render/api';
import * as import111 from '@angular/core/src/security';
import * as import112 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import113 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import114 from '@angular/http/src/interfaces';
import * as import115 from '@angular/http/src/http';
import * as import116 from '@angular/router/src/router_config_loader';
import * as import117 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import118 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _FlugModule_8:import9.FlugModule;
  _DefaultStyleCompatibilityModeModule_9:import10.DefaultStyleCompatibilityModeModule;
  _MdRippleModule_10:import11.MdRippleModule;
  _MdButtonModule_11:import12.MdButtonModule;
  _MdCardModule_12:import13.MdCardModule;
  _MdChipsModule_13:import14.MdChipsModule;
  _MdCheckboxModule_14:import15.MdCheckboxModule;
  _MdLineModule_15:import16.MdLineModule;
  _MdGridListModule_16:import17.MdGridListModule;
  _PlatformModule_17:import18.PlatformModule;
  _MdInputModule_18:import19.MdInputModule;
  _MdListModule_19:import20.MdListModule;
  _MdProgressBarModule_20:import21.MdProgressBarModule;
  _MdProgressSpinnerModule_21:import22.MdProgressSpinnerModule;
  _PortalModule_22:import23.PortalModule;
  _OverlayModule_23:import24.OverlayModule;
  _MdSelectModule_24:import25.MdSelectModule;
  _A11yModule_25:import26.A11yModule;
  _MdSidenavModule_26:import27.MdSidenavModule;
  _ObserveContentModule_27:import28.ObserveContentModule;
  _MdTabsModule_28:import29.MdTabsModule;
  _MdToolbarModule_29:import30.MdToolbarModule;
  _ProjectionModule_30:import31.ProjectionModule;
  _RtlModule_31:import32.RtlModule;
  _MdButtonToggleModule_32:import33.MdButtonToggleModule;
  _MdDialogModule_33:import34.MdDialogModule;
  _MdIconModule_34:import35.MdIconModule;
  _MdMenuModule_35:import36.MdMenuModule;
  _MdRadioModule_36:import37.MdRadioModule;
  _MdSliderModule_37:import38.MdSliderModule;
  _MdSlideToggleModule_38:import39.MdSlideToggleModule;
  _MdSnackBarModule_39:import40.MdSnackBarModule;
  _MdTooltipModule_40:import41.MdTooltipModule;
  _MaterialRootModule_41:import42.MaterialRootModule;
  _AppModule_42:import1.AppModule;
  __LOCALE_ID_43:any;
  __NgLocalization_44:import43.NgLocaleLocalization;
  _ErrorHandler_45:any;
  _ApplicationInitStatus_46:import44.ApplicationInitStatus;
  _Testability_47:import45.Testability;
  _ApplicationRef__48:import46.ApplicationRef_;
  __ApplicationRef_49:any;
  __Compiler_50:import47.Compiler;
  __APP_ID_51:any;
  __DOCUMENT_52:any;
  __HAMMER_GESTURE_CONFIG_53:import48.GestureConfig;
  __EVENT_MANAGER_PLUGINS_54:any[];
  __EventManager_55:import49.EventManager;
  __DomSharedStylesHost_56:import50.DomSharedStylesHost;
  __AnimationDriver_57:any;
  __DomRootRenderer_58:import51.DomRootRenderer_;
  __NgProbeToken_59:any[];
  __RootRenderer_60:any;
  __DomSanitizer_61:import52.DomSanitizerImpl;
  __Sanitizer_62:any;
  __AnimationQueue_63:import53.AnimationQueue;
  __ViewUtils_64:import54.ViewUtils;
  __IterableDiffers_65:any;
  __KeyValueDiffers_66:any;
  __SharedStylesHost_67:any;
  __Title_68:import55.Title;
  __BrowserXhr_69:import56.BrowserXhr;
  __ResponseOptions_70:import57.BaseResponseOptions;
  __XSRFStrategy_71:any;
  __XHRBackend_72:import58.XHRBackend;
  __RequestOptions_73:import59.BaseRequestOptions;
  __Http_74:any;
  __RadioControlRegistry_75:import60.RadioControlRegistry;
  __ROUTES_76:any[];
  __FlugService_77:import61.FlugService;
  __MATERIAL_COMPATIBILITY_MODE_78:any;
  __ViewportRuler_79:import62.ViewportRuler;
  __Platform_80:import63.Platform;
  __OverlayPositionBuilder_81:import64.OverlayPositionBuilder;
  __OverlayContainer_82:import65.OverlayContainer;
  __Overlay_83:import66.Overlay;
  __ScrollDispatcher_84:import67.ScrollDispatcher;
  __InteractivityChecker_85:import68.InteractivityChecker;
  __DomProjection_86:import31.DomProjection;
  __LiveAnnouncer_87:import69.LiveAnnouncer;
  __UniqueSelectionDispatcher_88:import70.UniqueSelectionDispatcher;
  __MdDialog_89:import71.MdDialog;
  __MdIconRegistry_90:import72.MdIconRegistry;
  __MdSnackBar_91:import40.MdSnackBar;
  __ROUTER_CONFIGURATION_92:any;
  __LocationStrategy_93:any;
  __Location_94:import73.Location;
  __UrlSerializer_95:import74.DefaultUrlSerializer;
  __RouterOutletMap_96:import75.RouterOutletMap;
  __NgModuleFactoryLoader_97:import76.SystemJsNgModuleLoader;
  __Router_98:any;
  __ActivatedRoute_99:any;
  _NoPreloading_100:import77.NoPreloading;
  _PreloadingStrategy_101:any;
  _RouterPreloader_102:import77.RouterPreloader;
  __PreloadAllModules_103:import77.PreloadAllModules;
  __ROUTER_INITIALIZER_104:any;
  __APP_BOOTSTRAP_LISTENER_105:any[];
  constructor(parent:import78.Injector) {
    super(parent,[
      import79.FlugBuchenComponentNgFactory,
      import80.FlugSuchenComponentNgFactory,
      import81.PassagierSuchenComponentNgFactory,
      import82.FlugEditComponentNgFactory,
      import83.MdDialogContainerNgFactory,
      import84.MdSnackBarContainerNgFactory,
      import85.SimpleSnackBarNgFactory,
      import86.TooltipComponentNgFactory,
      import87.HomeComponentNgFactory,
      import88.AppComponentNgFactory
    ]
    ,[import88.AppComponentNgFactory]);
  }
  get _LOCALE_ID_43():any {
    if ((this.__LOCALE_ID_43 == null)) { (this.__LOCALE_ID_43 = 'en-US'); }
    return this.__LOCALE_ID_43;
  }
  get _NgLocalization_44():import43.NgLocaleLocalization {
    if ((this.__NgLocalization_44 == null)) { (this.__NgLocalization_44 = new import43.NgLocaleLocalization(this._LOCALE_ID_43)); }
    return this.__NgLocalization_44;
  }
  get _ApplicationRef_49():any {
    if ((this.__ApplicationRef_49 == null)) { (this.__ApplicationRef_49 = this._ApplicationRef__48); }
    return this.__ApplicationRef_49;
  }
  get _Compiler_50():import47.Compiler {
    if ((this.__Compiler_50 == null)) { (this.__Compiler_50 = new import47.Compiler()); }
    return this.__Compiler_50;
  }
  get _APP_ID_51():any {
    if ((this.__APP_ID_51 == null)) { (this.__APP_ID_51 = import89._appIdRandomProviderFactory()); }
    return this.__APP_ID_51;
  }
  get _DOCUMENT_52():any {
    if ((this.__DOCUMENT_52 == null)) { (this.__DOCUMENT_52 = import4._document()); }
    return this.__DOCUMENT_52;
  }
  get _HAMMER_GESTURE_CONFIG_53():import48.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_53 == null)) { (this.__HAMMER_GESTURE_CONFIG_53 = new import48.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_53;
  }
  get _EVENT_MANAGER_PLUGINS_54():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_54 == null)) { (this.__EVENT_MANAGER_PLUGINS_54 = [
      new import90.DomEventsPlugin(),
      new import91.KeyEventsPlugin(),
      new import92.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_53)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_54;
  }
  get _EventManager_55():import49.EventManager {
    if ((this.__EventManager_55 == null)) { (this.__EventManager_55 = new import49.EventManager(this._EVENT_MANAGER_PLUGINS_54,this.parent.get(import93.NgZone))); }
    return this.__EventManager_55;
  }
  get _DomSharedStylesHost_56():import50.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_56 == null)) { (this.__DomSharedStylesHost_56 = new import50.DomSharedStylesHost(this._DOCUMENT_52)); }
    return this.__DomSharedStylesHost_56;
  }
  get _AnimationDriver_57():any {
    if ((this.__AnimationDriver_57 == null)) { (this.__AnimationDriver_57 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_57;
  }
  get _DomRootRenderer_58():import51.DomRootRenderer_ {
    if ((this.__DomRootRenderer_58 == null)) { (this.__DomRootRenderer_58 = new import51.DomRootRenderer_(this._DOCUMENT_52,this._EventManager_55,this._DomSharedStylesHost_56,this._AnimationDriver_57,this._APP_ID_51)); }
    return this.__DomRootRenderer_58;
  }
  get _NgProbeToken_59():any[] {
    if ((this.__NgProbeToken_59 == null)) { (this.__NgProbeToken_59 = [import8.routerNgProbeToken()]); }
    return this.__NgProbeToken_59;
  }
  get _RootRenderer_60():any {
    if ((this.__RootRenderer_60 == null)) { (this.__RootRenderer_60 = import94._createConditionalRootRenderer(this._DomRootRenderer_58,this.parent.get(import94.NgProbeToken,(null as any)),this._NgProbeToken_59)); }
    return this.__RootRenderer_60;
  }
  get _DomSanitizer_61():import52.DomSanitizerImpl {
    if ((this.__DomSanitizer_61 == null)) { (this.__DomSanitizer_61 = new import52.DomSanitizerImpl()); }
    return this.__DomSanitizer_61;
  }
  get _Sanitizer_62():any {
    if ((this.__Sanitizer_62 == null)) { (this.__Sanitizer_62 = this._DomSanitizer_61); }
    return this.__Sanitizer_62;
  }
  get _AnimationQueue_63():import53.AnimationQueue {
    if ((this.__AnimationQueue_63 == null)) { (this.__AnimationQueue_63 = new import53.AnimationQueue(this.parent.get(import93.NgZone))); }
    return this.__AnimationQueue_63;
  }
  get _ViewUtils_64():import54.ViewUtils {
    if ((this.__ViewUtils_64 == null)) { (this.__ViewUtils_64 = new import54.ViewUtils(this._RootRenderer_60,this._Sanitizer_62,this._AnimationQueue_63)); }
    return this.__ViewUtils_64;
  }
  get _IterableDiffers_65():any {
    if ((this.__IterableDiffers_65 == null)) { (this.__IterableDiffers_65 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_65;
  }
  get _KeyValueDiffers_66():any {
    if ((this.__KeyValueDiffers_66 == null)) { (this.__KeyValueDiffers_66 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_66;
  }
  get _SharedStylesHost_67():any {
    if ((this.__SharedStylesHost_67 == null)) { (this.__SharedStylesHost_67 = this._DomSharedStylesHost_56); }
    return this.__SharedStylesHost_67;
  }
  get _Title_68():import55.Title {
    if ((this.__Title_68 == null)) { (this.__Title_68 = new import55.Title()); }
    return this.__Title_68;
  }
  get _BrowserXhr_69():import56.BrowserXhr {
    if ((this.__BrowserXhr_69 == null)) { (this.__BrowserXhr_69 = new import56.BrowserXhr()); }
    return this.__BrowserXhr_69;
  }
  get _ResponseOptions_70():import57.BaseResponseOptions {
    if ((this.__ResponseOptions_70 == null)) { (this.__ResponseOptions_70 = new import57.BaseResponseOptions()); }
    return this.__ResponseOptions_70;
  }
  get _XSRFStrategy_71():any {
    if ((this.__XSRFStrategy_71 == null)) { (this.__XSRFStrategy_71 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_71;
  }
  get _XHRBackend_72():import58.XHRBackend {
    if ((this.__XHRBackend_72 == null)) { (this.__XHRBackend_72 = new import58.XHRBackend(this._BrowserXhr_69,this._ResponseOptions_70,this._XSRFStrategy_71)); }
    return this.__XHRBackend_72;
  }
  get _RequestOptions_73():import59.BaseRequestOptions {
    if ((this.__RequestOptions_73 == null)) { (this.__RequestOptions_73 = new import59.BaseRequestOptions()); }
    return this.__RequestOptions_73;
  }
  get _Http_74():any {
    if ((this.__Http_74 == null)) { (this.__Http_74 = import5.httpFactory(this._XHRBackend_72,this._RequestOptions_73)); }
    return this.__Http_74;
  }
  get _RadioControlRegistry_75():import60.RadioControlRegistry {
    if ((this.__RadioControlRegistry_75 == null)) { (this.__RadioControlRegistry_75 = new import60.RadioControlRegistry()); }
    return this.__RadioControlRegistry_75;
  }
  get _ROUTES_76():any[] {
    if ((this.__ROUTES_76 == null)) { (this.__ROUTES_76 = [
        [{
          path: 'flug-buchen',
          component: import95.FlugBuchenComponent,
          children: [
            {
              path: 'flug-suchen',
              component: import96.FlugSuchenComponent
            }
            ,
            {
              path: 'passagier-suchen',
              component: import97.PassagierSuchenComponent
            }
            ,
            {
              path: 'flug-edit/:id',
              component: import98.FlugEditComponent
            }

          ]

        }
      ],
      [
        {
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'home',
          component: import99.HomeComponent
        }
        ,
        {
          path: '**',
          redirectTo: 'home'
        }

      ]

    ]
    ); }
    return this.__ROUTES_76;
  }
  get _FlugService_77():import61.FlugService {
    if ((this.__FlugService_77 == null)) { (this.__FlugService_77 = new import61.FlugService(this._Http_74)); }
    return this.__FlugService_77;
  }
  get _MATERIAL_COMPATIBILITY_MODE_78():any {
    if ((this.__MATERIAL_COMPATIBILITY_MODE_78 == null)) { (this.__MATERIAL_COMPATIBILITY_MODE_78 = false); }
    return this.__MATERIAL_COMPATIBILITY_MODE_78;
  }
  get _ViewportRuler_79():import62.ViewportRuler {
    if ((this.__ViewportRuler_79 == null)) { (this.__ViewportRuler_79 = new import62.ViewportRuler()); }
    return this.__ViewportRuler_79;
  }
  get _Platform_80():import63.Platform {
    if ((this.__Platform_80 == null)) { (this.__Platform_80 = new import63.Platform()); }
    return this.__Platform_80;
  }
  get _OverlayPositionBuilder_81():import64.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_81 == null)) { (this.__OverlayPositionBuilder_81 = new import64.OverlayPositionBuilder(this._ViewportRuler_79)); }
    return this.__OverlayPositionBuilder_81;
  }
  get _OverlayContainer_82():import65.OverlayContainer {
    if ((this.__OverlayContainer_82 == null)) { (this.__OverlayContainer_82 = new import65.OverlayContainer()); }
    return this.__OverlayContainer_82;
  }
  get _Overlay_83():import66.Overlay {
    if ((this.__Overlay_83 == null)) { (this.__Overlay_83 = new import66.Overlay(this._OverlayContainer_82,this,this._OverlayPositionBuilder_81,this._ApplicationRef_49,this,this.parent.get(import93.NgZone))); }
    return this.__Overlay_83;
  }
  get _ScrollDispatcher_84():import67.ScrollDispatcher {
    if ((this.__ScrollDispatcher_84 == null)) { (this.__ScrollDispatcher_84 = new import67.ScrollDispatcher()); }
    return this.__ScrollDispatcher_84;
  }
  get _InteractivityChecker_85():import68.InteractivityChecker {
    if ((this.__InteractivityChecker_85 == null)) { (this.__InteractivityChecker_85 = new import68.InteractivityChecker(this._Platform_80)); }
    return this.__InteractivityChecker_85;
  }
  get _DomProjection_86():import31.DomProjection {
    if ((this.__DomProjection_86 == null)) { (this.__DomProjection_86 = new import31.DomProjection()); }
    return this.__DomProjection_86;
  }
  get _LiveAnnouncer_87():import69.LiveAnnouncer {
    if ((this.__LiveAnnouncer_87 == null)) { (this.__LiveAnnouncer_87 = new import69.LiveAnnouncer(this.parent.get(import69.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_87;
  }
  get _UniqueSelectionDispatcher_88():import70.UniqueSelectionDispatcher {
    if ((this.__UniqueSelectionDispatcher_88 == null)) { (this.__UniqueSelectionDispatcher_88 = new import70.UniqueSelectionDispatcher()); }
    return this.__UniqueSelectionDispatcher_88;
  }
  get _MdDialog_89():import71.MdDialog {
    if ((this.__MdDialog_89 == null)) { (this.__MdDialog_89 = new import71.MdDialog(this._Overlay_83,this)); }
    return this.__MdDialog_89;
  }
  get _MdIconRegistry_90():import72.MdIconRegistry {
    if ((this.__MdIconRegistry_90 == null)) { (this.__MdIconRegistry_90 = new import72.MdIconRegistry(this._Http_74,this._DomSanitizer_61)); }
    return this.__MdIconRegistry_90;
  }
  get _MdSnackBar_91():import40.MdSnackBar {
    if ((this.__MdSnackBar_91 == null)) { (this.__MdSnackBar_91 = new import40.MdSnackBar(this._Overlay_83,this._LiveAnnouncer_87)); }
    return this.__MdSnackBar_91;
  }
  get _ROUTER_CONFIGURATION_92():any {
    if ((this.__ROUTER_CONFIGURATION_92 == null)) { (this.__ROUTER_CONFIGURATION_92 = {}); }
    return this.__ROUTER_CONFIGURATION_92;
  }
  get _LocationStrategy_93():any {
    if ((this.__LocationStrategy_93 == null)) { (this.__LocationStrategy_93 = import8.provideLocationStrategy(this.parent.get(import100.PlatformLocation),this.parent.get(import101.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_92)); }
    return this.__LocationStrategy_93;
  }
  get _Location_94():import73.Location {
    if ((this.__Location_94 == null)) { (this.__Location_94 = new import73.Location(this._LocationStrategy_93)); }
    return this.__Location_94;
  }
  get _UrlSerializer_95():import74.DefaultUrlSerializer {
    if ((this.__UrlSerializer_95 == null)) { (this.__UrlSerializer_95 = new import74.DefaultUrlSerializer()); }
    return this.__UrlSerializer_95;
  }
  get _RouterOutletMap_96():import75.RouterOutletMap {
    if ((this.__RouterOutletMap_96 == null)) { (this.__RouterOutletMap_96 = new import75.RouterOutletMap()); }
    return this.__RouterOutletMap_96;
  }
  get _NgModuleFactoryLoader_97():import76.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_97 == null)) { (this.__NgModuleFactoryLoader_97 = new import76.SystemJsNgModuleLoader(this._Compiler_50,this.parent.get(import76.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_97;
  }
  get _Router_98():any {
    if ((this.__Router_98 == null)) { (this.__Router_98 = import8.setupRouter(this._ApplicationRef_49,this._UrlSerializer_95,this._RouterOutletMap_96,this._Location_94,this,this._NgModuleFactoryLoader_97,this._Compiler_50,this._ROUTES_76,this._ROUTER_CONFIGURATION_92,this.parent.get(import102.UrlHandlingStrategy,(null as any)),this.parent.get(import103.RouteReuseStrategy,(null as any)))); }
    return this.__Router_98;
  }
  get _ActivatedRoute_99():any {
    if ((this.__ActivatedRoute_99 == null)) { (this.__ActivatedRoute_99 = import8.rootRoute(this._Router_98)); }
    return this.__ActivatedRoute_99;
  }
  get _PreloadAllModules_103():import77.PreloadAllModules {
    if ((this.__PreloadAllModules_103 == null)) { (this.__PreloadAllModules_103 = new import77.PreloadAllModules()); }
    return this.__PreloadAllModules_103;
  }
  get _ROUTER_INITIALIZER_104():any {
    if ((this.__ROUTER_INITIALIZER_104 == null)) { (this.__ROUTER_INITIALIZER_104 = import8.initialRouterNavigation(this._Router_98,this._ApplicationRef_49,this._RouterPreloader_102,this._ROUTER_CONFIGURATION_92)); }
    return this.__ROUTER_INITIALIZER_104;
  }
  get _APP_BOOTSTRAP_LISTENER_105():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_105 == null)) { (this.__APP_BOOTSTRAP_LISTENER_105 = [this._ROUTER_INITIALIZER_104]); }
    return this.__APP_BOOTSTRAP_LISTENER_105;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import104.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._FlugModule_8 = new import9.FlugModule();
    this._DefaultStyleCompatibilityModeModule_9 = new import10.DefaultStyleCompatibilityModeModule();
    this._MdRippleModule_10 = new import11.MdRippleModule();
    this._MdButtonModule_11 = new import12.MdButtonModule();
    this._MdCardModule_12 = new import13.MdCardModule();
    this._MdChipsModule_13 = new import14.MdChipsModule();
    this._MdCheckboxModule_14 = new import15.MdCheckboxModule();
    this._MdLineModule_15 = new import16.MdLineModule();
    this._MdGridListModule_16 = new import17.MdGridListModule();
    this._PlatformModule_17 = new import18.PlatformModule();
    this._MdInputModule_18 = new import19.MdInputModule();
    this._MdListModule_19 = new import20.MdListModule();
    this._MdProgressBarModule_20 = new import21.MdProgressBarModule();
    this._MdProgressSpinnerModule_21 = new import22.MdProgressSpinnerModule();
    this._PortalModule_22 = new import23.PortalModule();
    this._OverlayModule_23 = new import24.OverlayModule();
    this._MdSelectModule_24 = new import25.MdSelectModule();
    this._A11yModule_25 = new import26.A11yModule();
    this._MdSidenavModule_26 = new import27.MdSidenavModule();
    this._ObserveContentModule_27 = new import28.ObserveContentModule();
    this._MdTabsModule_28 = new import29.MdTabsModule();
    this._MdToolbarModule_29 = new import30.MdToolbarModule();
    this._ProjectionModule_30 = new import31.ProjectionModule();
    this._RtlModule_31 = new import32.RtlModule();
    this._MdButtonToggleModule_32 = new import33.MdButtonToggleModule();
    this._MdDialogModule_33 = new import34.MdDialogModule();
    this._MdIconModule_34 = new import35.MdIconModule();
    this._MdMenuModule_35 = new import36.MdMenuModule();
    this._MdRadioModule_36 = new import37.MdRadioModule();
    this._MdSliderModule_37 = new import38.MdSliderModule();
    this._MdSlideToggleModule_38 = new import39.MdSlideToggleModule();
    this._MdSnackBarModule_39 = new import40.MdSnackBarModule();
    this._MdTooltipModule_40 = new import41.MdTooltipModule();
    this._MaterialRootModule_41 = new import42.MaterialRootModule();
    this._AppModule_42 = new import1.AppModule();
    this._ErrorHandler_45 = import4.errorHandler();
    this._ApplicationInitStatus_46 = new import44.ApplicationInitStatus(this.parent.get(import44.APP_INITIALIZER,(null as any)));
    this._Testability_47 = new import45.Testability(this.parent.get(import93.NgZone));
    this._ApplicationRef__48 = new import46.ApplicationRef_(this.parent.get(import93.NgZone),this.parent.get(import105.Console),this,this._ErrorHandler_45,this,this._ApplicationInitStatus_46,this.parent.get(import45.TestabilityRegistry,(null as any)),this._Testability_47);
    this._NoPreloading_100 = new import77.NoPreloading();
    this._PreloadingStrategy_101 = this._NoPreloading_100;
    this._RouterPreloader_102 = new import77.RouterPreloader(this._Router_98,this._NgModuleFactoryLoader_97,this._Compiler_50,this,this._PreloadingStrategy_101);
    return this._AppModule_42;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.FlugModule)) { return this._FlugModule_8; }
    if ((token === import10.DefaultStyleCompatibilityModeModule)) { return this._DefaultStyleCompatibilityModeModule_9; }
    if ((token === import11.MdRippleModule)) { return this._MdRippleModule_10; }
    if ((token === import12.MdButtonModule)) { return this._MdButtonModule_11; }
    if ((token === import13.MdCardModule)) { return this._MdCardModule_12; }
    if ((token === import14.MdChipsModule)) { return this._MdChipsModule_13; }
    if ((token === import15.MdCheckboxModule)) { return this._MdCheckboxModule_14; }
    if ((token === import16.MdLineModule)) { return this._MdLineModule_15; }
    if ((token === import17.MdGridListModule)) { return this._MdGridListModule_16; }
    if ((token === import18.PlatformModule)) { return this._PlatformModule_17; }
    if ((token === import19.MdInputModule)) { return this._MdInputModule_18; }
    if ((token === import20.MdListModule)) { return this._MdListModule_19; }
    if ((token === import21.MdProgressBarModule)) { return this._MdProgressBarModule_20; }
    if ((token === import22.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_21; }
    if ((token === import23.PortalModule)) { return this._PortalModule_22; }
    if ((token === import24.OverlayModule)) { return this._OverlayModule_23; }
    if ((token === import25.MdSelectModule)) { return this._MdSelectModule_24; }
    if ((token === import26.A11yModule)) { return this._A11yModule_25; }
    if ((token === import27.MdSidenavModule)) { return this._MdSidenavModule_26; }
    if ((token === import28.ObserveContentModule)) { return this._ObserveContentModule_27; }
    if ((token === import29.MdTabsModule)) { return this._MdTabsModule_28; }
    if ((token === import30.MdToolbarModule)) { return this._MdToolbarModule_29; }
    if ((token === import31.ProjectionModule)) { return this._ProjectionModule_30; }
    if ((token === import32.RtlModule)) { return this._RtlModule_31; }
    if ((token === import33.MdButtonToggleModule)) { return this._MdButtonToggleModule_32; }
    if ((token === import34.MdDialogModule)) { return this._MdDialogModule_33; }
    if ((token === import35.MdIconModule)) { return this._MdIconModule_34; }
    if ((token === import36.MdMenuModule)) { return this._MdMenuModule_35; }
    if ((token === import37.MdRadioModule)) { return this._MdRadioModule_36; }
    if ((token === import38.MdSliderModule)) { return this._MdSliderModule_37; }
    if ((token === import39.MdSlideToggleModule)) { return this._MdSlideToggleModule_38; }
    if ((token === import40.MdSnackBarModule)) { return this._MdSnackBarModule_39; }
    if ((token === import41.MdTooltipModule)) { return this._MdTooltipModule_40; }
    if ((token === import42.MaterialRootModule)) { return this._MaterialRootModule_41; }
    if ((token === import1.AppModule)) { return this._AppModule_42; }
    if ((token === import106.LOCALE_ID)) { return this._LOCALE_ID_43; }
    if ((token === import43.NgLocalization)) { return this._NgLocalization_44; }
    if ((token === import107.ErrorHandler)) { return this._ErrorHandler_45; }
    if ((token === import44.ApplicationInitStatus)) { return this._ApplicationInitStatus_46; }
    if ((token === import45.Testability)) { return this._Testability_47; }
    if ((token === import46.ApplicationRef_)) { return this._ApplicationRef__48; }
    if ((token === import46.ApplicationRef)) { return this._ApplicationRef_49; }
    if ((token === import47.Compiler)) { return this._Compiler_50; }
    if ((token === import89.APP_ID)) { return this._APP_ID_51; }
    if ((token === import108.DOCUMENT)) { return this._DOCUMENT_52; }
    if ((token === import92.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_53; }
    if ((token === import49.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_54; }
    if ((token === import49.EventManager)) { return this._EventManager_55; }
    if ((token === import50.DomSharedStylesHost)) { return this._DomSharedStylesHost_56; }
    if ((token === import109.AnimationDriver)) { return this._AnimationDriver_57; }
    if ((token === import51.DomRootRenderer)) { return this._DomRootRenderer_58; }
    if ((token === import46.NgProbeToken)) { return this._NgProbeToken_59; }
    if ((token === import110.RootRenderer)) { return this._RootRenderer_60; }
    if ((token === import52.DomSanitizer)) { return this._DomSanitizer_61; }
    if ((token === import111.Sanitizer)) { return this._Sanitizer_62; }
    if ((token === import53.AnimationQueue)) { return this._AnimationQueue_63; }
    if ((token === import54.ViewUtils)) { return this._ViewUtils_64; }
    if ((token === import112.IterableDiffers)) { return this._IterableDiffers_65; }
    if ((token === import113.KeyValueDiffers)) { return this._KeyValueDiffers_66; }
    if ((token === import50.SharedStylesHost)) { return this._SharedStylesHost_67; }
    if ((token === import55.Title)) { return this._Title_68; }
    if ((token === import56.BrowserXhr)) { return this._BrowserXhr_69; }
    if ((token === import57.ResponseOptions)) { return this._ResponseOptions_70; }
    if ((token === import114.XSRFStrategy)) { return this._XSRFStrategy_71; }
    if ((token === import58.XHRBackend)) { return this._XHRBackend_72; }
    if ((token === import59.RequestOptions)) { return this._RequestOptions_73; }
    if ((token === import115.Http)) { return this._Http_74; }
    if ((token === import60.RadioControlRegistry)) { return this._RadioControlRegistry_75; }
    if ((token === import116.ROUTES)) { return this._ROUTES_76; }
    if ((token === import61.FlugService)) { return this._FlugService_77; }
    if ((token === import10.MATERIAL_COMPATIBILITY_MODE)) { return this._MATERIAL_COMPATIBILITY_MODE_78; }
    if ((token === import62.ViewportRuler)) { return this._ViewportRuler_79; }
    if ((token === import63.Platform)) { return this._Platform_80; }
    if ((token === import64.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_81; }
    if ((token === import65.OverlayContainer)) { return this._OverlayContainer_82; }
    if ((token === import66.Overlay)) { return this._Overlay_83; }
    if ((token === import67.ScrollDispatcher)) { return this._ScrollDispatcher_84; }
    if ((token === import68.InteractivityChecker)) { return this._InteractivityChecker_85; }
    if ((token === import31.DomProjection)) { return this._DomProjection_86; }
    if ((token === import69.LiveAnnouncer)) { return this._LiveAnnouncer_87; }
    if ((token === import70.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_88; }
    if ((token === import71.MdDialog)) { return this._MdDialog_89; }
    if ((token === import72.MdIconRegistry)) { return this._MdIconRegistry_90; }
    if ((token === import40.MdSnackBar)) { return this._MdSnackBar_91; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_92; }
    if ((token === import101.LocationStrategy)) { return this._LocationStrategy_93; }
    if ((token === import73.Location)) { return this._Location_94; }
    if ((token === import74.UrlSerializer)) { return this._UrlSerializer_95; }
    if ((token === import75.RouterOutletMap)) { return this._RouterOutletMap_96; }
    if ((token === import117.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_97; }
    if ((token === import104.Router)) { return this._Router_98; }
    if ((token === import118.ActivatedRoute)) { return this._ActivatedRoute_99; }
    if ((token === import77.NoPreloading)) { return this._NoPreloading_100; }
    if ((token === import77.PreloadingStrategy)) { return this._PreloadingStrategy_101; }
    if ((token === import77.RouterPreloader)) { return this._RouterPreloader_102; }
    if ((token === import77.PreloadAllModules)) { return this._PreloadAllModules_103; }
    if ((token === import8.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_104; }
    if ((token === import89.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_105; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__48.ngOnDestroy();
    this._RouterPreloader_102.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);