/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/flug/flug-suchen/flug-suchen.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/flug/services/flug.service';
import * as import9 from './flug-suchen.component.css.shim.ngstyle';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/router/src/directives/router_link';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import19 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import20 from '../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import21 from '../../validators/ort.validator.directive.ngfactory';
import * as import22 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import25 from '@angular/common/src/pipes/date_pipe';
import * as import26 from '../../../../app/pipes/city.pipe';
import * as import27 from '@angular/common/src/pipes/json_pipe';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from '@angular/core/src/linker/template_ref';
import * as import30 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import31 from '@angular/core/src/i18n/tokens';
import * as import32 from '@angular/forms/src/directives/default_value_accessor';
import * as import33 from '@angular/forms/src/directives/validators';
import * as import34 from '../../../../app/validators/ort.validator.directive';
import * as import35 from '@angular/forms/src/validators';
import * as import36 from '@angular/forms/src/directives/control_value_accessor';
import * as import37 from '@angular/forms/src/directives/ng_model';
import * as import38 from '@angular/forms/src/directives/ng_control';
import * as import39 from '@angular/forms/src/directives/ng_control_status';
import * as import40 from '@angular/common/src/directives/ng_if';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from '@angular/forms/src/directives/ng_form';
import * as import43 from '@angular/forms/src/directives/control_container';
export class Wrapper_FlugSuchenComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FlugSuchenComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.FlugSuchenComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FlugSuchenComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FlugSuchenComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FlugSuchenComponent>;
  _FlugSuchenComponent_0_3:Wrapper_FlugSuchenComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugSuchenComponent_Host0,renderType_FlugSuchenComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'flug-suchen',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FlugSuchenComponent0(this.viewUtils,this,0,this._el_0);
    this._FlugSuchenComponent_0_3 = new Wrapper_FlugSuchenComponent(this.injectorGet(import8.FlugService,this.parentIndex));
    this.compView_0.create(this._FlugSuchenComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FlugSuchenComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FlugSuchenComponent) && (0 === requestNodeIndex))) { return this._FlugSuchenComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FlugSuchenComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FlugSuchenComponentNgFactory:import7.ComponentFactory<import0.FlugSuchenComponent> = new import7.ComponentFactory<import0.FlugSuchenComponent>('flug-suchen',View_FlugSuchenComponent_Host0,import0.FlugSuchenComponent);
const styles_FlugSuchenComponent:any[] = [import9.styles];
class View_FlugSuchenComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent1,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Fehlerhafte Eingabe!\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent2,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Pflichtfeld!\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent3,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Muss min. 3 Zeichen haben!\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent4,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Darf max. 3 Zeichen haben!\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent5,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Nur Buchstaben erlaubt!\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent6,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Ort existiert nicht! (Mögliche Werte: Graz, Hamburg)\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent7,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        Ort wird nicht angeflogen! (Mögliche Werte: Graz, Hamburg)\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent8,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'marquee',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            Validierung wird durchgeführt!\n        ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_FlugSuchenComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import11.Wrapper_RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_28:any;
  _pipe_city_1_0:any;
  /*private*/ _expr_30:any;
  _pipe_city_1_1:any;
  _arr_32:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_FlugSuchenComponent9,renderType_FlugSuchenComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_24 = import12.UNINITIALIZED;
    this._expr_25 = import12.UNINITIALIZED;
    this._expr_26 = import12.UNINITIALIZED;
    this._expr_28 = import12.UNINITIALIZED;
    this._expr_30 = import12.UNINITIALIZED;
    this._arr_32 = import3.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Auswählen',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,' |\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_14,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_19_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import13.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import14.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import15.LocationStrategy,this.parentView.parentIndex));
    this._text_20 = this.renderer.createText(this._el_19,'Edit',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._pipe_date_0_0 = import3.pureProxy2((<View_FlugSuchenComponent0>this.parentView)._pipe_date_0.transform.bind((<View_FlugSuchenComponent0>this.parentView)._pipe_date_0));
    this._pipe_city_1_0 = import3.pureProxy1((<View_FlugSuchenComponent0>this.parentView)._pipe_city_1.transform.bind((<View_FlugSuchenComponent0>this.parentView)._pipe_city_1));
    this._pipe_city_1_1 = import3.pureProxy1((<View_FlugSuchenComponent0>this.parentView)._pipe_city_1.transform.bind((<View_FlugSuchenComponent0>this.parentView)._pipe_city_1));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import12.ValueUnwrapper();
    const currVal_19_0_0:any = this._arr_32('../flug-edit',this.context.$implicit.id);
    this._RouterLinkWithHref_19_3.check_routerLink(currVal_19_0_0,throwOnChange,false);
    this._RouterLinkWithHref_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_24:any = (this.context.$implicit == this.parentView.context.selectedFlug);
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import3.inlineInterpolate(1,'',this.context.$implicit.id,'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_3,currVal_25);
      this._expr_25 = currVal_25;
    }
    valUnwrapper.reset();
    const currVal_26:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_0_0,(<View_FlugSuchenComponent0>this.parentView)._pipe_date_0.transform)(this.context.$implicit.datum,'dd.MM.yyyy')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_26,currVal_26))) {
      this.renderer.setText(this._text_6,currVal_26);
      this._expr_26 = currVal_26;
    }
    valUnwrapper.reset();
    const currVal_28:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_city_1_0,(<View_FlugSuchenComponent0>this.parentView)._pipe_city_1.transform)(this.context.$implicit.abflugort)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_28,currVal_28))) {
      this.renderer.setText(this._text_9,currVal_28);
      this._expr_28 = currVal_28;
    }
    valUnwrapper.reset();
    const currVal_30:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_city_1_1,(<View_FlugSuchenComponent0>this.parentView)._pipe_city_1.transform)(this.context.$implicit.zielort)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_30,currVal_30))) {
      this.renderer.setText(this._text_12,currVal_30);
      this._expr_30 = currVal_30;
    }
    this._RouterLinkWithHref_19_3.checkHost(this,this,this._el_19,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.select(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
var renderType_FlugSuchenComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_FlugSuchenComponent,{});
export class View_FlugSuchenComponent0 extends import1.AppView<import0.FlugSuchenComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _NgForm_3_3:import17.Wrapper_NgForm;
  _ControlContainer_3_4:any;
  _NgControlStatusGroup_3_5:import18.Wrapper_NgControlStatusGroup;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import19.Wrapper_DefaultValueAccessor;
  _RequiredValidator_10_4:import20.Wrapper_RequiredValidator;
  _MinLengthValidator_10_5:import20.Wrapper_MinLengthValidator;
  _MaxLengthValidator_10_6:import20.Wrapper_MaxLengthValidator;
  _PatternValidator_10_7:import20.Wrapper_PatternValidator;
  _OrtValidatorDirective_10_8:import21.Wrapper_OrtValidatorDirective;
  _NG_VALIDATORS_10_9:any[];
  _NG_VALUE_ACCESSOR_10_10:any[];
  _NgModel_10_11:import22.Wrapper_NgModel;
  _NgControl_10_12:any;
  _NgControlStatus_10_13:import18.Wrapper_NgControlStatus;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import10.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import23.Wrapper_NgIf;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import10.ViewContainer;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import23.Wrapper_NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import10.ViewContainer;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import23.Wrapper_NgIf;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _vc_19:import10.ViewContainer;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import23.Wrapper_NgIf;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import10.ViewContainer;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import23.Wrapper_NgIf;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import10.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import23.Wrapper_NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import10.ViewContainer;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import23.Wrapper_NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _vc_27:import10.ViewContainer;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import23.Wrapper_NgIf;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import19.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _NgModel_34_5:import22.Wrapper_NgModel;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import18.Wrapper_NgControlStatus;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _anchor_46:any;
  /*private*/ _vc_46:import10.ViewContainer;
  _TemplateRef_46_5:any;
  _NgFor_46_6:import24.Wrapper_NgFor;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  /*private*/ _expr_98:any;
  _pipe_date_0:import25.DatePipe;
  _pipe_city_1:import26.CityPipe;
  /*private*/ _expr_101:any;
  _pipe_json_2:import27.JsonPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FlugSuchenComponent0,renderType_FlugSuchenComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_98 = import12.UNINITIALIZED;
    this._expr_101 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Flug suchen!!!',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_3_3 = new import17.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_3_4 = this._NgForm_3_3.context;
    this._NgControlStatusGroup_3_5 = new import18.Wrapper_NgControlStatusGroup(this._ControlContainer_3_4);
    this._text_4 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Von:',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_5,'input',new import3.InlineArray16(16,'class','form-control','maxlength','30','minlength','3','name','von','ort','Graz,München,Hamburg,Frankfurt,Zürich,Wien','pattern','^\\w+$','required','','xortAsync',''),(null as any));
    this._DefaultValueAccessor_10_3 = new import19.Wrapper_DefaultValueAccessor(this.renderer,new import28.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import20.Wrapper_RequiredValidator();
    this._MinLengthValidator_10_5 = new import20.Wrapper_MinLengthValidator();
    this._MaxLengthValidator_10_6 = new import20.Wrapper_MaxLengthValidator();
    this._PatternValidator_10_7 = new import20.Wrapper_PatternValidator();
    this._OrtValidatorDirective_10_8 = new import21.Wrapper_OrtValidatorDirective();
    this._NG_VALIDATORS_10_9 = [
      this._RequiredValidator_10_4.context,
      this._MinLengthValidator_10_5.context,
      this._MaxLengthValidator_10_6.context,
      this._PatternValidator_10_7.context,
      this._OrtValidatorDirective_10_8.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_10_10 = [this._DefaultValueAccessor_10_3.context];
    this._NgModel_10_11 = new import22.Wrapper_NgModel(this._ControlContainer_3_4,this._NG_VALIDATORS_10_9,(null as any),this._NG_VALUE_ACCESSOR_10_10);
    this._NgControl_10_12 = this._NgModel_10_11.context;
    this._NgControlStatus_10_13 = new import18.Wrapper_NgControlStatus(this._NgControl_10_12);
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_13 = new import10.ViewContainer(13,3,this,this._anchor_13);
    this._TemplateRef_13_5 = new import29.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import23.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_15 = new import10.ViewContainer(15,3,this,this._anchor_15);
    this._TemplateRef_15_5 = new import29.TemplateRef_(this,15,this._anchor_15);
    this._NgIf_15_6 = new import23.Wrapper_NgIf(this._vc_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_17 = new import10.ViewContainer(17,3,this,this._anchor_17);
    this._TemplateRef_17_5 = new import29.TemplateRef_(this,17,this._anchor_17);
    this._NgIf_17_6 = new import23.Wrapper_NgIf(this._vc_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_19 = new import10.ViewContainer(19,3,this,this._anchor_19);
    this._TemplateRef_19_5 = new import29.TemplateRef_(this,19,this._anchor_19);
    this._NgIf_19_6 = new import23.Wrapper_NgIf(this._vc_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_21 = new import10.ViewContainer(21,3,this,this._anchor_21);
    this._TemplateRef_21_5 = new import29.TemplateRef_(this,21,this._anchor_21);
    this._NgIf_21_6 = new import23.Wrapper_NgIf(this._vc_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_23 = new import10.ViewContainer(23,3,this,this._anchor_23);
    this._TemplateRef_23_5 = new import29.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import23.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_25 = new import10.ViewContainer(25,3,this,this._anchor_25);
    this._TemplateRef_25_5 = new import29.TemplateRef_(this,25,this._anchor_25);
    this._NgIf_25_6 = new import23.Wrapper_NgIf(this._vc_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_27 = new import10.ViewContainer(27,3,this,this._anchor_27);
    this._TemplateRef_27_5 = new import29.TemplateRef_(this,27,this._anchor_27);
    this._NgIf_27_6 = new import23.Wrapper_NgIf(this._vc_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Nach:',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_29,'input',new import3.InlineArray4(4,'class','form-control','name','nach'),(null as any));
    this._DefaultValueAccessor_34_3 = new import19.Wrapper_DefaultValueAccessor(this.renderer,new import28.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3.context];
    this._NgModel_34_5 = new import22.Wrapper_NgModel(this._ControlContainer_3_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._NgModel_34_5.context;
    this._NgControlStatus_34_7 = new import18.Wrapper_NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'button',new import3.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n            Suchen!\n        ',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_3,'table',new import3.InlineArray2(2,'class','table table-striped'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_45,(null as any));
    this._vc_46 = new import10.ViewContainer(46,45,this,this._anchor_46);
    this._TemplateRef_46_5 = new import29.TemplateRef_(this,46,this._anchor_46);
    this._NgFor_46_6 = new import24.Wrapper_NgFor(this._vc_46.vcRef,this._TemplateRef_46_5,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.ref);
    this._text_47 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_3,'\n\n',(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,parentRenderNode,'pre',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_3));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_11.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_34,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_34));
    this._NgModel_34_5.subscribe(this,this.eventHandler(this.handleEvent_34),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    this._pipe_date_0 = new import25.DatePipe(this.parentView.injectorGet(import31.LOCALE_ID,this.parentIndex));
    this._pipe_city_1 = new import26.CityPipe();
    this._pipe_json_2 = new import27.JsonPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._anchor_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3.context; }
    if (((token === import33.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4.context; }
    if (((token === import33.MinLengthValidator) && (10 === requestNodeIndex))) { return this._MinLengthValidator_10_5.context; }
    if (((token === import33.MaxLengthValidator) && (10 === requestNodeIndex))) { return this._MaxLengthValidator_10_6.context; }
    if (((token === import33.PatternValidator) && (10 === requestNodeIndex))) { return this._PatternValidator_10_7.context; }
    if (((token === import34.OrtValidatorDirective) && (10 === requestNodeIndex))) { return this._OrtValidatorDirective_10_8.context; }
    if (((token === import35.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_9; }
    if (((token === import36.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_10; }
    if (((token === import37.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_11.context; }
    if (((token === import38.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_12; }
    if (((token === import39.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_13.context; }
    if (((token === import29.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import40.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import29.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import40.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import29.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import40.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import29.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import40.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6.context; }
    if (((token === import29.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import40.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import29.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import40.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import29.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import40.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import29.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import40.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    if (((token === import32.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3.context; }
    if (((token === import36.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import37.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_5.context; }
    if (((token === import38.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import39.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7.context; }
    if (((token === import29.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import41.NgFor) && (46 === requestNodeIndex))) { return this._NgFor_46_6.context; }
    if (((token === import42.NgForm) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgForm_3_3.context; }
    if (((token === import43.ControlContainer) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ControlContainer_3_4; }
    if (((token === import39.NgControlStatusGroup) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgControlStatusGroup_3_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import12.ValueUnwrapper();
    this._NgForm_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._NgControlStatusGroup_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    this._DefaultValueAccessor_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = '';
    this._RequiredValidator_10_4.check_required(currVal_10_1_0,throwOnChange,false);
    this._RequiredValidator_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_2_0:any = '3';
    this._MinLengthValidator_10_5.check_minlength(currVal_10_2_0,throwOnChange,false);
    this._MinLengthValidator_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_3_0:any = '30';
    this._MaxLengthValidator_10_6.check_maxlength(currVal_10_3_0,throwOnChange,false);
    this._MaxLengthValidator_10_6.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_4_0:any = '^\\w+$';
    this._PatternValidator_10_7.check_pattern(currVal_10_4_0,throwOnChange,false);
    this._PatternValidator_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_5_0:any = 'Graz,München,Hamburg,Frankfurt,Zürich,Wien';
    this._OrtValidatorDirective_10_8.check_ort(currVal_10_5_0,throwOnChange,false);
    this._OrtValidatorDirective_10_8.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_6_0:any = 'von';
    this._NgModel_10_11.check_name(currVal_10_6_0,throwOnChange,false);
    const currVal_10_6_1:any = this.context.von;
    this._NgModel_10_11.check_model(currVal_10_6_1,throwOnChange,false);
    this._NgModel_10_11.ngDoCheck(this,this._el_10,throwOnChange);
    this._NgControlStatus_10_13.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_13_0_0:boolean = !((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].valid));
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    const currVal_15_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('required')));
    this._NgIf_15_6.check_ngIf(currVal_15_0_0,throwOnChange,false);
    this._NgIf_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    const currVal_17_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('minlength')));
    this._NgIf_17_6.check_ngIf(currVal_17_0_0,throwOnChange,false);
    this._NgIf_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    const currVal_19_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('maxlength')));
    this._NgIf_19_6.check_ngIf(currVal_19_0_0,throwOnChange,false);
    this._NgIf_19_6.ngDoCheck(this,this._anchor_19,throwOnChange);
    const currVal_21_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('pattern')));
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    const currVal_23_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('ort')));
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    const currVal_25_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].hasError('ortAsync')));
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    const currVal_27_0_0:any = ((this._NgForm_3_3.context == null)? (null as any): ((this._NgForm_3_3.context.controls['von'] == null)? (null as any): this._NgForm_3_3.context.controls['von'].pending));
    this._NgIf_27_6.check_ngIf(currVal_27_0_0,throwOnChange,false);
    this._NgIf_27_6.ngDoCheck(this,this._anchor_27,throwOnChange);
    this._DefaultValueAccessor_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_34_1_0:any = 'nach';
    this._NgModel_34_5.check_name(currVal_34_1_0,throwOnChange,false);
    const currVal_34_1_1:any = this.context.nach;
    this._NgModel_34_5.check_model(currVal_34_1_1,throwOnChange,false);
    this._NgModel_34_5.ngDoCheck(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_7.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_46_0_0:any = this.context.fluege;
    this._NgFor_46_6.check_ngForOf(currVal_46_0_0,throwOnChange,false);
    this._NgFor_46_6.ngDoCheck(this,this._anchor_46,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    this._vc_19.detectChangesInNestedViews(throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    this._vc_27.detectChangesInNestedViews(throwOnChange);
    this._vc_46.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_3_5.checkHost(this,this,this._el_3,throwOnChange);
    this._RequiredValidator_10_4.checkHost(this,this,this._el_10,throwOnChange);
    this._MinLengthValidator_10_5.checkHost(this,this,this._el_10,throwOnChange);
    this._MaxLengthValidator_10_6.checkHost(this,this,this._el_10,throwOnChange);
    this._PatternValidator_10_7.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_10_13.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_34_7.checkHost(this,this,this._el_34,throwOnChange);
    const currVal_98:boolean = (!this.context.von || !this.context.nach);
    if (import3.checkBinding(throwOnChange,this._expr_98,currVal_98)) {
      this.renderer.setElementProperty(this._el_39,'disabled',currVal_98);
      this._expr_98 = currVal_98;
    }
    valUnwrapper.reset();
    const currVal_101:any = import3.inlineInterpolate(1,'Warenkorb\n----------------------\n',valUnwrapper.unwrap(this._pipe_json_2.transform(this.context.selectedFlug)),'\n');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_101,currVal_101))) {
      this.renderer.setText(this._text_51,currVal_101);
      this._expr_101 = currVal_101;
    }
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_15.destroyNestedViews();
    this._vc_17.destroyNestedViews();
    this._vc_19.destroyNestedViews();
    this._vc_21.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._vc_27.destroyNestedViews();
    this._vc_46.destroyNestedViews();
    this._NgModel_10_11.ngOnDestroy();
    this._NgModel_34_5.ngOnDestroy();
    this._NgForm_3_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_FlugSuchenComponent1(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 15)) { return new View_FlugSuchenComponent2(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    if ((nodeIndex == 17)) { return new View_FlugSuchenComponent3(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    if ((nodeIndex == 19)) { return new View_FlugSuchenComponent4(this.viewUtils,this,19,this._anchor_19,this._vc_19); }
    if ((nodeIndex == 21)) { return new View_FlugSuchenComponent5(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    if ((nodeIndex == 23)) { return new View_FlugSuchenComponent6(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 25)) { return new View_FlugSuchenComponent7(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    if ((nodeIndex == 27)) { return new View_FlugSuchenComponent8(this.viewUtils,this,27,this._anchor_27,this._vc_27); }
    if ((nodeIndex == 46)) { return new View_FlugSuchenComponent9(this.viewUtils,this,46,this._anchor_46,this._vc_46); }
    return (null as any);
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_3_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.von = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_34(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_34_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.nach = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.suchen()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}